apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata: 
  name: {{ .Release.Name }}-prod-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: danohavran@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx