version: '3.4'

services:
  django:
    image: django-docker:1
    build:
      context: django_docker/
      dockerfile: Dockerfile
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DB_IP
      - DJANGO_ALLOWED_HOSTS
    ports:
      - 80:8000
    restart: always
    networks:
      - private.app
      - public.app
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - PGDATA:/var/lib/postgresql/data
    networks:
      - private.app
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    volumes:
      - PGADATA:/var/lib/pgadmin
    networks:
      - private.app
      - public.app

networks:
  private.app:
    driver: bridge
    internal: true
  public.app:
    driver: bridge

volumes:
  PGDATA:
  PGADATA:
