replicaCount: 2

image:
  repository: bohdan004/django-docker
  pullPolicy: Always
  tag: "1.0"
  port: 8000

service:
  type: ClusterIP
  port: 8080

host: django.dns.navy

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

