apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekV3TVRBeApNalU0TWpoYUZ3MDBNekV3TVRBeE1qVTRNamhhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDa1kwamJGSTdOR1pTQllTNjFDV05aYjV5Umhkd1lialdodG5hR2E3L0NDMm5LYU1rMApMYW5RcnhHY1NwR011V0FwbGVGSSs1bHNDUDd2VXcyMXZZUEltbEVIWGw5bTkweHhvdmtwNlNlYlUwNndLemx0CnFCN0xYblQ3VHpURi96ODFYWmN2eEZnUEJsWVZ3cFhKU1p4QWVwVnpUM2w4cnlmNnoydDRZNVl5RlNrSUdjc2UKcVZaQ2o1Rjl5UlVyVko5eHhZUjdSTFNJU3VWMmF3VktlL0VJc3hYQi9VYkpiVzIzN3ZMRDVHUFFWdTZzYWRETApjYWZIN2NNc0JPZlM5RUEwTG1zdTVMRjF3MmxFdDd5cXFubDNDYXBCT0JSdVpkZHF0QW0zRTdkTTlPQ3MyZVZQCmFDTUtBSmZ3QTlFQXRSOHVPZTUyUlYzcTM2bnN6VzFUTFgzSkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFUaFE1L2hhek0xb3pnMjJNRgpUcEhGTnBwd0pUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFFY2hxdVllOVBBVmlzcU5mYnZYL2s4T1pWbEJ6ClFzamd2MkVhT3orTnlzRkVzeTlwQjhzNXFSdHhUbEJiZ2Vubm9JNk44M2Y2RXZ0VFF4OUR1alpYSkt1Qm52c2oKcFhIejYvcm53My9RTmdUL1NBVm1ibW8vZEZxd0RwUkxVeUpMdXo5OUs5M2VYZEVNWko2Y0VYdEdkSzFVZ29tMwpXL3k4TlpORnIwK3Q1M0pRZVFWVnI3SlZXM2tleHNiQlpQMHVuamhFNFdBbmhta01qRnVNaVhMamVuZkFEOUZDCjJJanBjMCtNUUdPeE5zOURyOFduNXRJRGxWU1k4cmVOckp1TWJ5THhYN3JLaXNOamM2QW9HVTZkdEc4K2wyYysKSmRnZm5wTThMOEw3bFl2M1FEeEp5R244T0p0c3NpcWs0cWVvQVNIRTVYYzZEWkFFY0NpeGVCU2FZQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://7568862c-43cd-4cb5-b0de-bd9a56f93b68.k8s.ondigitalocean.com
  name: do-nyc1-django
contexts:
- context:
    cluster: do-nyc1-django
    user: do-nyc1-django-admin
  name: do-nyc1-django
current-context: do-nyc1-django
users:
- name: do-nyc1-django-admin
  user:
    token: dop_v1_3d5f07be4e301682279dcc52e3aa51fc3c4913878782c506f87f6e033829b031
